<#
.SYNOPSIS
    Seeds product images for the 15 Walmal Sport demo products (V17 catalog).

.DESCRIPTION
    V17__reseed_sports_catalog.sql renames the original 5 demo products to
    sports products, adds 10 more (15 total) and deletes their old
    product_images rows, so primaryImageUrl is null and the storefront/admin
    show "No image" placeholders. This script uploads a matching PNG (from
    scripts/seed-images/, generated by scripts/generate-seed-images.py) for
    each product via POST /api/v1/product/{productId}/images (multipart,
    admin/staff JWT required) and marks it primary in the same call.

    IDEMPOTENT: for each product it first calls GET .../images and skips the
    upload if the product already has a PRIMARY image (not just any image —
    stray non-primary images can be left behind by other test suites, e.g.
    the admin E2E product-CRUD spec, and must not block seeding a real
    primary). Safe to re-run.

    Re-run this after a postgres/minio volume wipe (docker compose down -v)
    or any time the 15 demo products come back imageless.

.PARAMETER ApiBase
    Base URL of the backend API. Defaults to http://localhost:8080/api/v1.

.EXAMPLE
    pwsh -File scripts/seed-product-images.ps1
#>

param(
    [string]$ApiBase = "http://localhost:8080/api/v1"
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ImagesDir = Join-Path $ScriptDir "seed-images"

# productId -> image filename (relative to seed-images/), from V17 seed data.
$Products = [ordered]@{
    "10000000-0000-0000-0000-000000000001" = "velocity-elite-fg-boot.png"     # Velocity Elite FG Boot
    "10000000-0000-0000-0000-000000000002" = "phantom-strike-fg-boot.png"     # Phantom Strike FG Boot
    "10000000-0000-0000-0000-000000000003" = "pro-match-goal.png"             # Pro Match Goal
    "10000000-0000-0000-0000-000000000004" = "harbour-city-fan-tee.png"       # Harbour City Fan Tee
    "10000000-0000-0000-0000-000000000005" = "dna-training-pants.png"         # DNA Training Pants
    "10000000-0000-0000-0000-000000000006" = "hc-home-jersey.png"             # HC Home Jersey
    "10000000-0000-0000-0000-000000000007" = "hc-away-jersey.png"             # HC Away Jersey
    "10000000-0000-0000-0000-000000000008" = "riverside-home-jersey.png"      # Riverside Home Jersey
    "10000000-0000-0000-0000-000000000009" = "national-authentic-jersey.png"  # National Authentic Jersey
    "10000000-0000-0000-0000-000000000010" = "aero-knit-speed-boot.png"       # Aero Knit Speed Boot
    "10000000-0000-0000-0000-000000000011" = "velocity-pro-ag-boot.png"       # Velocity Pro AG Boot
    "10000000-0000-0000-0000-000000000012" = "match-ball.png"                 # Match Ball
    "10000000-0000-0000-0000-000000000013" = "grip-training-socks.png"        # Grip Training Socks
    "10000000-0000-0000-0000-000000000014" = "lite-carbon-shinguards.png"     # Lite Carbon Shinguards
    "10000000-0000-0000-0000-000000000015" = "dna-training-polo.png"          # DNA Training Polo
}

Write-Host "Logging in as admin_test..."
$loginBody = @{ username = "admin_test"; password = "AdminPass123!" } | ConvertTo-Json
$tokenResponse = Invoke-RestMethod -Method Post -Uri "$ApiBase/auth/login" `
    -ContentType "application/json" -Body $loginBody
$accessToken = $tokenResponse.accessToken
if (-not $accessToken) {
    throw "Login did not return an accessToken. Response: $($tokenResponse | ConvertTo-Json -Compress)"
}
$authHeader = @{ Authorization = "Bearer $accessToken" }

foreach ($productId in $Products.Keys) {
    $imageFile = Join-Path $ImagesDir $Products[$productId]
    if (-not (Test-Path $imageFile)) {
        Write-Host "[$productId] SKIP - image file not found: $imageFile"
        continue
    }

    # Idempotency check: skip only if a PRIMARY image already exists. Stray
    # non-primary images (e.g. leftover from admin E2E CRUD tests) must not
    # block seeding a real primary image for the storefront.
    $existing = Invoke-RestMethod -Method Get -Uri "$ApiBase/product/$productId/images"
    $existingImages = $existing.data
    $hasPrimary = $existingImages | Where-Object { $_.primary -eq $true }
    if ($hasPrimary) {
        Write-Host "[$productId] SKIPPED (already has a primary image)"
        continue
    }

    # Multipart upload via curl.exe (Windows ships curl.exe; more reliable than
    # Invoke-RestMethod -Form across PowerShell 5.1/7 for multipart + auth headers).
    $result = & curl.exe -s -X POST "$ApiBase/product/$productId/images" `
        -H "Authorization: Bearer $accessToken" `
        -F "file=@$imageFile;type=image/png" `
        -F "isPrimary=true"

    if ($result -match '"storageKey"') {
        Write-Host "[$productId] UPLOADED - $($Products[$productId]) (set as primary)"
    } else {
        Write-Host "[$productId] FAILED - response: $result"
    }
}

Write-Host "Done."
